{"uid":"609aab2feeb85590","name":"Test create user","fullName":"tests.test_users.TestUsersAPI#test_create_user","historyId":"7906fed064abe2a7a41f166381015ab4","time":{"start":1733086962888,"stop":1733086962889,"duration":1},"description":"Verify user creation and data validation","descriptionHtml":"<p>Verify user creation and data validation</p>\n","status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short","statusTrace":"self = <tests.test_users.TestUsersAPI object at 0x7f75ce784410>\nnew_user = {'avatar_url': '', 'email': 'todd80@example.com', 'name': 'Anna', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n>               UserResponse.model_validate(user)\nE               pydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:112: ValidationError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.test_users.TestUsersAPI object at 0x7f75ce784410>\nnew_user = {'avatar_url': '', 'email': 'todd80@example.com', 'name': 'Anna', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n                UserResponse.model_validate(user)\n            except ValidationError as e:\n                msg = f\"User data validation failed: {e}\"\n>               raise AssertionError(msg) from e\nE               AssertionError: User data validation failed: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:115: AssertionError","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"pytestconfig","time":{"start":1733086956518,"stop":1733086956518,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"base_url","time":{"start":1733086956519,"stop":1733086956519,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"delete_output_dir","time":{"start":1733086956519,"stop":1733086956519,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_session_faker","time":{"start":1733086956519,"stop":1733086956520,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_verify_url","time":{"start":1733086956519,"stop":1733086956519,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright","time":{"start":1733086956520,"stop":1733086956756,"duration":236},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"api_request_context","time":{"start":1733086956756,"stop":1733086956764,"duration":8},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"user_api_client","time":{"start":1733086962530,"stop":1733086962530,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"new_user","time":{"start":1733086962530,"stop":1733086962888,"duration":358},"status":"passed","steps":[],"attachments":[{"uid":"892a67af303d7ab2","name":"API Response","source":"892a67af303d7ab2.txt","type":"text/plain","size":151},{"uid":"ef88c174416d5e5b","name":"Status Code","source":"ef88c174416d5e5b.txt","type":"text/plain","size":3},{"uid":"bf4c04e3436a1440","name":"Headers","source":"bf4c04e3436a1440.txt","type":"text/plain","size":648},{"uid":"561fa406cfaba81f","name":"URL","source":"561fa406cfaba81f.txt","type":"text/plain","size":45}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":4,"hasContent":true,"attachmentStep":false}],"testStage":{"description":"Verify user creation and data validation","status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short","statusTrace":"self = <tests.test_users.TestUsersAPI object at 0x7f75ce784410>\nnew_user = {'avatar_url': '', 'email': 'todd80@example.com', 'name': 'Anna', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n>               UserResponse.model_validate(user)\nE               pydantic_core._pydantic_core.ValidationError: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:112: ValidationError\n\nThe above exception was the direct cause of the following exception:\n\nself = <tests.test_users.TestUsersAPI object at 0x7f75ce784410>\nnew_user = {'avatar_url': '', 'email': 'todd80@example.com', 'name': 'Anna', 'nickname': '', ...}\n\n    @allure.title(\"Test create user\")\n    @allure.description(\"Verify user creation and data validation\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_create_user(self, new_user: dict) -> None:\n        \"\"\"\n        Test creating a new user.\n    \n        :param new_user: Fixture with a newly created user\n        \"\"\"\n        with allure.step(\"Validating newly created user data\"):\n            user = new_user\n    \n            try:\n                UserResponse.model_validate(user)\n            except ValidationError as e:\n                msg = f\"User data validation failed: {e}\"\n>               raise AssertionError(msg) from e\nE               AssertionError: User data validation failed: 1 validation error for UserResponse\nE               nickname\nE                 String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\nE                   For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n\ntests/test_users.py:115: AssertionError","steps":[{"name":"Validating newly created user data","time":{"start":1733086962888,"stop":1733086962889,"duration":1},"status":"failed","statusMessage":"AssertionError: User data validation failed: 1 validation error for UserResponse\nnickname\n  String should have at least 2 characters [type=string_too_short, input_value='', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_too_short\n","statusTrace":"  File \"/home/runner/work/qa-hackathon-raptors/qa-hackathon-raptors/tests/test_users.py\", line 115, in test_create_user\n    raise AssertionError(msg) from e\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"new_user::0","time":{"start":1733086962893,"stop":1733086963505,"duration":612},"status":"passed","steps":[],"attachments":[{"uid":"712ba371367198af","name":"API Response","source":"712ba371367198af.txt","type":"text/plain","size":14},{"uid":"5181838dd303a637","name":"Status Code","source":"5181838dd303a637.txt","type":"text/plain","size":3},{"uid":"89cbebd2e90638b2","name":"Headers","source":"89cbebd2e90638b2.txt","type":"text/plain","size":579},{"uid":"41e1597274c6b1e8","name":"URL","source":"41e1597274c6b1e8.txt","type":"text/plain","size":82}],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":4,"hasContent":true,"attachmentStep":false},{"name":"api_request_context::0","time":{"start":1733086963719,"stop":1733086963722,"duration":3},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"playwright::0","time":{"start":1733086963722,"stop":1733086963728,"duration":6},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"feature","value":"User API Operations"},{"name":"severity","value":"critical"},{"name":"epic","value":"User Management"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsersAPI"},{"name":"host","value":"fv-az1442-141"},{"name":"thread","value":"5573-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"new_user","value":"'api-3'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"9ebf44839eca9f9c","reportUrl":"https://ZhikharevAl.github.io/qa-hackathon-raptors/2//#testresult/9ebf44839eca9f9c","status":"broken","statusDetails":"ValueError: Request failed with status 404","time":{"start":1733086643809,"stop":1733086643809,"duration":0}},{"uid":"da5b9c0ad993a9bb","reportUrl":"https://ZhikharevAl.github.io/qa-hackathon-raptors/1//#testresult/da5b9c0ad993a9bb","status":"passed","time":{"start":1733085920247,"stop":1733085920247,"duration":0}}]},"tags":[]},"source":"609aab2feeb85590.json","parameterValues":["'api-3'"]}